server:
  port: 8080

spring:
  application:
    name: booking-system-api
  app:
    jwt:
      password: d2Fzd29uZGVyZmlsbG5vaXNlc3BsaXRjcm93ZHNob3R1bmRlcmFycm93dGhyb3VnaG7=
      expiration-time: 8.64e+7
  
  datasource:
    url: jdbc:mysql://localhost:3306/booking_system?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  cache:
    type: redis
    redis:
      time-to-live: 600000
  data:
    redis:
      host: localhost
      port: 6379
      password: redis_password

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

app:
  email:
    verification-url: http://localhost:8080/api/auth/verify-email
  booking:
    cancellation-hours: 4
    checkin-before-minutes: 15
    checkin-after-minutes: 30
    booking-cutoff-minutes: 30
  scheduler:
    enabled: true

logging:
  level:
    com.app.booking: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    root: INFO